### ISSUE TITLE
null变量引用

### ISSUE THREAD

**Issue by shaoshuai0102** [fool2fish/velocity#26]
js 中 a 变量为null

在模板中使用

    $!a

正确的方式是输出空，但是实际输出了 `null`

undefined的处理没问题

**Comment by fengmk2** [comment]
这是 nunjuck 的问题。。。我们解决吧

**Comment by shaoshuai0102** [comment]
跟junjucks木关系啊，我已经找到方式了，PRing

**Comment by fengmk2** [comment]
ok
