### ISSUE TITLE
不支持相对路径的引入吗？

### ISSUE THREAD

**Issue by leeluolee** [fool2fish/velocity#28]
比如  
```
template/vm
├── inc.vm
└── index.vm
```
在index.vm中

```
#parse("./inc.vm")
```

提示

```
#parse("inc.vm")
       ^^^^^^^^
Error: Param of #parse not exists or is not subpath of root.
    at /Users/leeluolee/code/wdp/test/template/vm/index.vm (16:7)
```

必须传入root参数？

**Comment by bengle** [comment]
碰到同样的问题
Error: Illegal context: #parse('../layout/header.vm')
<h1>Hello World!</h1>
#parse('../layout/footer.vm')
怎么破？

**Comment by leeluolee** [comment]
看了下， java的标准版也是不支持的。。。  很诡异，  还是老老实实传root吧

**Comment by bengle** [comment]
好吧，还是老老实实传root吧

**Comment by fool2fish** [comment]
嗯，velocity 是个很老的模板，必须要传 root，这个版本和 java 版本在最大限度上保持了一致，不一致的地方可以参看  https://github.com/fool2fish/velocity/blob/master/docs/differ-from-java-edition.md
