### ISSUE TITLE
vm npm package

### ISSUE THREAD

**Issue by jcrben** [fool2fish/velocity#29]
I stumbled across this because someone on my team seems to have (accidentally) installed the 'vm' package which is here: https://www.npmjs.com/package/vm

It redirects to this github repo but it appears to be basically dead, and the bin file is simply console.log('Place holder').

Should it be taken down from npm?

**Comment by jsw0528** [comment]
Why not install `velocity` package directly?

**Comment by jcrben** [comment]
We don't need velocity. It was someone's mistake. But why have a placeholder `vm` package on npm? Note also that placeholder packages violate npm guidelines.

**Comment by fool2fish** [comment]
vm was the ex name of this repo, I had already unpublished this package

**Comment by jcrben** [comment]
Thanks for unpublishing the package. :+1:
