### ISSUE TITLE
缩进换行问题

### ISSUE THREAD

**Issue by calledT** [fool2fish/velocity#31]
判断语句或者macro方法执行后，输出的内容会有多余的换行或者缩进，这不是我想要的，有什么办法能去掉吗？
![IMG](http://ww2.sinaimg.cn/large/68250c36gw1ev5wxj2lkfj20ch01ymxc.jpg)

**Comment by fool2fish** [comment]
快速解决方案：自己过滤下空白行？

这种情况要处理会比较麻烦，所以我可能不会在引擎中修改，举几个例子你就知道了：

```
## 情况1 
#if(...) ... #else ... #end

## 情况2
... #if(...) ...
...
#else ... #end

## 情况3
#if
...
#else
...
#end
```

**Comment by calledT** [comment]
源码为了阅读都是有一定格式的，所以自己把源码的空白行去掉不利于代码的阅读。像你列举的这几种情况，不能在进行render的时候把空格和空白行用正则匹配替换掉吗，情况2和3可以变成情况1的样子的吧？空白行或者空格的输出会影响到内容在页面上的展示。

**Comment by jsw0528** [comment]
空行、空格只能自己去除，因为 JAVA 渲染也是没有去除的，得保持一致性
