### ISSUE TITLE
没明白这个插件的作用

### ISSUE THREAD

**Issue by MarvinXu** [fool2fish/velocity#35]
我没用明白，只能解析vm输出到console吗？
不能在浏览器里预览没什么用啊

**Comment by jsw0528** [comment]
这不是「插件」，这是 JS 版的 Velocity 模板解析引擎。

要把编译后的 HTML 怎么输出，是你自己要做的事。

比如可以用 Koa，然后模板可以用 `.vm` 文件。就像 JAVA 的 Spring 那样。

**Comment by MarvinXu** [comment]
感谢这么快的回复。因为最近在尝试模板解耦，在找一个插件能让前端独立完成vm模板的编写，并能mock数据调试，不太懂node，所以才有这个问题，我再回去研究研究~

**Comment by jsw0528** [comment]
跟，这事我两年前就做了。Java 有自己的 MVC 系统，但对前端不友好，也不方便 mock 调试。所以本地跑 koa 服务，模板直接用线上拉下来的。但由于跟内部系统强耦合，所以给不了你参考，自己摸索吧

**Comment by jsw0528** [comment]
总之，如果你想脱离 JAVA 渲染 Velocity 模板，用这个绝对没错！
